### ISSUE TITLE
Additional Features?

### ISSUE THREAD

**Issue by tingles2233** [meri-imperiumi/signalk-triplogger#63]
Hi Henri, 

I love this addon and where it could go. 

Is there a way to have it log additional nema sensors every time we create a log entry? For example I would like to record the fuel levels and oil pressures, Temperatures,  RPM of the engines everytime there is a log entry or at regular intervals (Example every 15 minutes)

Could we also have the fields logged an shown if we click on the entry but on the logbook view only show certain entries?

Also I love the idea of having node-red trigger log entries 

MVEudora
www.mveudora.com

**Comment by bergie** [comment]
Yes, we could expand the schema. However, you’re in the wrong repository. This right one is https://github.com/meri-imperiumi/signalk-logbook
